apiVersion: v1
kind: Pod
metadata:
  name: b-app
spec:

  initContainers:
    - name: configurer
      image: busybox:1.32.0
      command: ['sh', '-c','mkdir -p /usr/shared/app && echo hello  > /usr/shared/app/config.json']
      #command: ['sh','-C','mkdir -p /usr/shared/app && echo hello  > /usr/shared/app/config.json']
      
      volumeMounts:
        - name: configdir
          mountPath: "/usr/shared/app"

  containers:

    - name: web
      image: bmuschko/nodejs-read-config:1.0.0
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP

      volumeMounts:
        - name: configdir
          mountPath: /usr/shared/app
        
  volumes:
    - name: configdir
      emptyDir: {}


