apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: secret-volume
          mountPath: /etc/secret
      resources:
        requests:
          cpu: "0.2"
          memory: "512m"
        limits:
          cpu: "1"
          memory: "1024m"
  volumes:
    - name: config-volume
      configMap:
        name: backend-config
    - name: secret-volume
      secret:
        secretName: config-secret

