apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
  labels:
    env: dev
    tier: backend
spec:

 

  containers:

    - name: liveness
      image: k8s.gcr.io/liveness

      args:
        - /server
        
      livenessProbe:
       
        httpGet:
          path: /healthz
          port: 8080
          httpdHeaders:
            - name: Custome-Header
              value: Awsome
       
        initialDelaySeconds: 3
        periodSeconds: 3


     
     

      
  
  